services:
  - type: web
    name: churn-dashboard
    env: python
    buildCommand: pip install -r requirements.txt && python master_pipeline.py
    startCommand: streamlit run src/dashboard/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: churn-api
    env: python
    buildCommand: pip install -r requirements.txt && python master_pipeline.py
    startCommand: uvicorn src.dashboard.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
